name = "cohere"
language = "rust"
type = "actor"
version = "0.1.0"

[actor]
claims = ["cosmonic:samples:chatlog", "wasmcloud:keyvalue",  "wasmcloud:builtin:logging", "wasmcloud:httpclient"]
call_alias = "mcchat/cohere"